#!name=Twitter Dim 深蓝主题
#!desc=恢复 X(Twitter) 深蓝主题（QX一键版）
#!system=iOS

[rewrite_local]

^https:\/\/(mobile\.)?(twitter|x)\.com\/.* url script-response-body x-dim

[script_local]

x-dim = type=http-response,pattern=^https:\/\/(mobile\.)?(twitter|x)\.com\/.*,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/zhangdi1309/11111/master/TwitterDim,script-update-interval=86400

[mitm]

hostname = twitter.com, mobile.twitter.com, x.com, mobile.x.com
